[package]
name = "brian-s-brain"
version = "0.1.0"
edition = "2021"
authors = ["Cyprien Borée <cyprien.boree@tuta.io>"]

[dependencies]
array2d = "0.2.1"
clap = { version = "4.0.18", features = ["derive"] }
vulkano = "0.32.0"
vulkano-win = "0.32.0"
winit = "0.27.5"